version: "3"

services:
  asterisk:
    image: asterisk
    ports:
      - "8088:8088"
      - "10000-10050:10000-10050/udp"
    volumes:
      - ./asterisk:/etc/asterisk
      - ./asterisk/keys:/etc/asterisk/keys
      - ./asterisk/sounds:/var/lib/asterisk/sounds
      - ./asterisk/agi-bin:/var/lib/asterisk/agi-bin
      - ./asterisk/spool:/var/spool/asterisk
      - ./asterisk/log:/var/log/asterisk
