version: "3"

services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile
    image: asterisk
    ports:
      - "5060:5060/udp" # SIP
      - "8088:8088" # PJSIP WebSocket
      - "10000-10050:10000-10050/udp" # RTP
    volumes:
      - ./asterisk:/etc/asterisk
      - ./asterisk/keys:/etc/asterisk/keys
      - ./asterisk/sounds:/var/lib/asterisk/sounds
      - ./asterisk/agi-bin:/var/lib/asterisk/agi-bin
      - ./asterisk/spool:/var/spool/asterisk
      - ./asterisk/log:/var/log/asterisk
