version: "3"

services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile
    image: asterisk
    network_mode: host
    volumes:
      - ./asterisk:/etc/asterisk
      - ./asterisk/keys:/etc/asterisk/keys
      - ./asterisk/sounds:/var/lib/asterisk/sounds
      - ./asterisk/agi-bin:/var/lib/asterisk/agi-bin
      - ./asterisk/spool:/var/spool/asterisk
      - ./asterisk/log:/var/log/asterisk
